heckj/swiftui-notes

- .travis.yml
- README.md
- docs/git.adoc
- docs/lib/git-metadata-preprocessor.rb
- docs/lib/git-metadata-preprocessor/extension.rb
- docs/lib/git-metadata-preprocessor/sample.adoc
- docs/using-combine-book.adoc
adds plugin/extension and renders git metadata associated with the source
> Git metadata

- docs/coreconcepts.adoc
- docs/reference.adoc
Thank you for writing all of this down and sharing it with the community, @heckj!
> Fix typo in spelling of notification

- docs/introduction.adoc
> Fixing "is gets" typo

- docs/patterns.adoc
thank you to Daniel Bauke for pointing it out
> Reflecting tryCatch disappearing from beta2

- SwiftUI-NotesTests/CombinePatternTests.swift
- docs/aboutthisbook.adoc
- docs/coreconcepts.adoc
- docs/introduction.adoc
- docs/pattern-template.adoc
- docs/patterns.adoc
- docs/reference.adoc
- docs/using-combine-book.adoc
- fixed some bits and pieces, and made notes of future work for other edits
> doing an existing content edit pass while I wait for structural feedback

- docs/coreconcepts.adoc
- docs/feedback.adoc
- docs/pattern-template.adoc
- docs/patterns.adoc
- fleshing/stubbing out the initial set of patterns to explore
- apply a formatting pattern to each of the patterns
- re-organize things a bit to see how it plays forward
> constraining feedback Q's and starting to apply received feedback

- SwiftUI-Notes.xcodeproj/project.pbxproj
- SwiftUI-Notes.xcodeproj/xcshareddata/xcschemes/SwiftUI-Notes.xcscheme
- SwiftUI-NotesTests/CombinePatternTests.swift
- UsingCombineTests/Info.plist
- UsingCombineTests/SinkSubscriberTests.swift
- UsingCombineTests/SubscribeReceiveAssignTests.swift
- UsingCombineTests/XCTestCase+KVOExpectatio0n.swift
- docs/patterns.adoc
- docs/reference-template.adoc
- docs/reference.adoc
- docs/using-combine-book.adoc
> sink pattern and reference updates

- UsingCombineTests/DataTaskPublisherTests.swift
- docs/coreconcepts.adoc
- docs/patterns.adoc
- docs/reference-template.adoc
- docs/reference.adoc
- docs/using-combine-book.adoc
> error handling updates and revisions, with reference links

- SwiftUI-Notes.xcodeproj/project.pbxproj
- SwiftUI-NotesTests/CombinePatternTests.swift
- UIKit-Combine/GithubAPI.swift
- UIKit-Combine/LocationHeadingProxy.swift
- UIKit-Combine/ViewController.swift
- UsingCombineTests/FuturePublisherTests.swift
- docs/coreconcepts.adoc
- docs/patterns.adoc
- docs/reference.adoc
- docs/using-combine-book.adoc
> starting into Future.publisher

- SwiftUI-Notes.xcodeproj/project.pbxproj
- UIKit-Combine/Base.lproj/Main.storyboard
- UIKit-Combine/GithubViewController.swift
- UIKit-Combine/HeadingViewController.swift
- UIKit-Combine/Info.plist
- UIKit-Combine/LocationHeadingProxy.swift
- docs/pattern-cascading-update-interface.adoc
- docs/pattern-delegate-publisher-subject.adoc
- docs/reference.adoc
- docs/using-combine-book.adoc
- sample code for repeating publisher wrapped around delegate object
resolves #39
> wrapped delegate example - with corelocation

- docs/pattern-test-pipeline-expectation.adoc
- docs/pattern-test-subscriber-subject.adoc
> explain using an XCTestExpectation with a pipeline

- docs/pattern-oneshot-error-handling.adoc
**Fix typo**: spelling of _choose_
> fix typo error of choose

- UsingCombineTests/SubscribeReceiveAssignTests.swift
- UsingCombineTests/debounceAndRemoveDuplicatesPublisherTests.swift
expanding on the tests validating what threads are executing operators
> Thread hopping

- docs/reference.adoc
updating a bit more from the beta4 release
> documentation ref found in beta4

- SwiftUI-Notes.xcodeproj/project.pbxproj
- SwiftUI-Notes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- UIKit-Combine/Base.lproj/Main.storyboard
- UIKit-Combine/FormViewController.swift
- UsingCombineTests/EntwineTestExampleTests.swift
- docs/coreconcepts.adoc
- docs/pattern-cascading-update-interface.adoc
- docs/pattern-merging-streams-interface.adoc
- docs/pattern-test-entwine.adoc
- docs/patterns.adoc
- docs/reference.adoc
resolves #41 
resolves #52 as well
> Uikit form validation

- docs/coreconcepts.adoc
> Typo: noticationcenter -> notificationcenter

- docs/pattern-datataskpublisher-decode.adoc
- docs/pattern-datataskpublisher-trymap.adoc
fixes double .sink operators in datataskpublisher patterns
> double .sink Operator in datataskpublisher patterns

- SwiftUI-Notes.xcodeproj/project.pbxproj
- UsingCombineTests/EntwineTestExampleTests.swift
- UsingCombineTests/InterimTestingStructs.swift
- UsingCombineTests/MergingPipelineTests.swift
> working on using EntwineTest to test CombineLatest

- UIKit-Combine/GithubViewController.swift
> typo pipeline

- UIKit-Combine/GithubViewController.swift
- UsingCombineTests/SubscribeReceiveAssignTests.swift
- docs/pattern-cascading-update-interface.adoc
- docs/reference.adoc
> Assign update

- README.md
- docs/coreconcepts.adoc
> clearing final link issues (for now)

- docs/coreconcepts.adoc
- docs/pattern-assign.adoc
- docs/pattern-test-subscriber-subject.adoc
- docs/reference.adoc
Hi and thank you for taking the time in writing this book!
I've spotted a few minor errors here and there and this PR fixes that.
Lastly I'd like to point out that in the chapter `Lifecycle of Publishers and Subscribers` the concept of Demand is introduced, more specifically with this sentence: 
```
When a subscriber is connected to a publisher, it requests data based with a specfic Demand.
```
However [Apple documentation](https://developer.apple.com/documentation/combine/subscribers/demand) has completely removed any trace of this Demand. I'm not sure if it's worth creating an issue in this repo, as Combine has changed quite a bit among beta releases and the book is not yet in the final version.
Regardless, I wanted to make sure you're aware of this :)
Again thank you so much for …
> Small fixes

- docs/coreconcepts.adoc
- docs/developingwith.adoc
- docs/pattern-assertnofailure.adoc
- docs/pattern-assign.adoc
- docs/pattern-cascading-update-interface.adoc
- docs/pattern-constrained-network.adoc
- docs/pattern-continual-error-handling.adoc
- docs/pattern-datataskpublisher-decode.adoc
- docs/pattern-datataskpublisher-trymap.adoc
- docs/pattern-debugging-pipelines-breakpoint.adoc
- docs/pattern-debugging-pipelines-handleevents.adoc
- docs/pattern-debugging-pipelines-print.adoc
- docs/pattern-delegate-publisher-subject.adoc
- docs/pattern-future.adoc
- docs/pattern-merging-streams-interface.adoc
- docs/pattern-notificationcenter.adoc
- docs/pattern-oneshot-error-handling.adoc
- docs/pattern-retry.adoc
- docs/pattern-sequencing-operations.adoc
- docs/pattern-sink.adoc
- docs/pattern-test-entwine.adoc
- docs/pattern-test-pipeline-expectation.adoc
- docs/pattern-test-subscriber-scheduled.adoc
- docs/pattern-test-subscriber-subject.adoc
- docs/pattern-update-interface-userinput.adoc
- docs/patterns.adoc
- docs/reference.adoc
- links.txt
to work around epub rendering issue
resolves #98
> adding explicit xref label text for cross references 

- .github/workflows/blank.yml
- .gitignore
- .travis.yml
- docs/aboutthisbook.adoc
- docs/images/diagrams/endings.svg
- docs/images/diagrams/test_example.svg
- marbles/README.md
- marbles/diagrams/newtest.txt
- marbles/diagrams/test.txt
- marbles/requirements.txt
- marbles/test.txt
- re.bash
working on enabling marble diagrams to support the operator documentation
resolves #107
> Diagram test

- docs/aboutthisbook.adoc
thanks for mentioning me! this is very much appreciated. But it's Michel not Michael
> fixed: the name is michel

- docs/aboutthisbook.adoc
more clearly denote the intermediate level of this book, reference some possible earlier tutorial books by other authors. Fixes #111
> more clearly denote the intermediate level of this book

- docs/coreconcepts.adoc
- docs/introduction.adoc
adding in some external resource links:
- stackoverflow
- swift forums
> resource links

- UsingCombineTests/FuturePublisherTests.swift
- docs/pattern-retry.adoc
- docs/reference.adoc
> update the retry docs re: optional count value (no longer correct)

- docs/coreconcepts.adoc
> Fix typo in coreconcepts.adoc

- docs/coreconcepts.adoc
> Fix typos in coreconcepts.adoc

- SwiftUI-Notes/ContentView.swift
- docs/coreconcepts.adoc
> fixing incorrect code sample for SwiftUI

- UsingCombineTests/FuturePublisherTests.swift
- docs/pattern-future.adoc
> adding in detail about resolved futures

- docs/coreconcepts.adoc
> updating grammar and fixing a typo

- docs/coreconcepts.adoc
> Fixed "opertions"

- SwiftUI-Notes.xcodeproj/project.pbxproj
- UsingCombineTests/ChangingErrorTests.swift
- docs/reference.adoc
> mapError and replaceError

- SwiftUI-Notes.xcodeproj/project.pbxproj
- UsingCombineTests/ChangingErrorTests.swift
- UsingCombineTests/FilteringOperatorTests.swift
- docs/reference.adoc
> filtering operator tests

- SwiftUI-Notes.xcodeproj/project.pbxproj
- UsingCombineTests/MathOperatorTests.swift
- docs/coreconcepts.adoc
- docs/reference.adoc
> math operators

- SwiftUI-Notes.xcodeproj/project.pbxproj
- UsingCombineTests/CriteriaOperatorTests.swift
- docs/reference.adoc
> Criteria operators

- SwiftUI-Notes.xcodeproj/project.pbxproj
- UsingCombineTests/DebounceAndRemoveDuplicatesPublisherTests.swift
- UsingCombineTests/SequencePublisherTests.swift
- UsingCombineTests/SequentialOperatorTests.swift
- docs/coreconcepts.adoc
- docs/reference.adoc
> Sequential operators

- docs/coreconcepts.adoc
> fix suggested by OskarPeredo

- SwiftUI-NotesTests/SwiftUI_CombineTests.swift
- UIKit-Combine/GithubViewController.swift
- UsingCombineTests/CriteriaOperatorTests.swift
- UsingCombineTests/DebounceAndRemoveDuplicatesPublisherTests.swift
- UsingCombineTests/FilteringOperatorTests.swift
- UsingCombineTests/MathOperatorTests.swift
- UsingCombineTests/MeasureIntervalTests.swift
- UsingCombineTests/ReducingOperatorTests.swift
- UsingCombineTests/SequentialOperatorTests.swift
- docs/coreconcepts.adoc
- docs/pattern-cascading-update-interface.adoc
- docs/pattern-debugging-pipelines-print.adoc
- docs/pattern-delegate-publisher-subject.adoc
- docs/reference.adoc
> surprisingly consistent in mispelling of propagate

- UsingCombineTests/MulticastSharePublisherTests.swift
- docs/aboutthisbook.adoc
- docs/coreconcepts.adoc
- docs/developingwith.adoc
- docs/introduction.adoc
- docs/pattern-assertnofailure.adoc
- docs/pattern-cascading-update-interface.adoc
- docs/pattern-continual-error-handling.adoc
- docs/pattern-datataskpublisher-trymap.adoc
- docs/pattern-debugging-pipelines-handleevents.adoc
- docs/pattern-debugging-pipelines-print.adoc
- docs/pattern-delegate-publisher-subject.adoc
- docs/pattern-merging-streams-interface.adoc
- docs/pattern-observableobject.adoc
- docs/pattern-retry.adoc
- docs/pattern-sequencing-operations.adoc
- docs/pattern-test-entwine.adoc
- docs/pattern-test-subscriber-scheduled.adoc
- docs/pattern-test-subscriber-subject.adoc
- docs/pattern-update-interface-userinput.adoc
- docs/patterns.adoc
- docs/reference.adoc
Minor typos I found while reading.
> Typo corrections

- SwiftUI-Notes/ReactiveFormModel.swift
> made comment references to embedded publisher provided by @Published

- UIKit-Combine/GithubViewController.swift
> simplifying logic now that sink returns an AnyCancellable

- docs/reference.adoc
- docs/using-combine-book.adoc
> updating error msg, verifying the whole kit in Xcode 11.7

- SwiftUI-Notes.xcodeproj/project.pbxproj
- UsingCombineTests/MergeManyPublisherTests.swift
- docs/reference.adoc
Hi! Your repo is awesome, it helps me a lot with understanding a combine, so i want to add a tiny but helpful guide.
I am not so good in forming thought in english, hope on your support with mr :)
> add MergeMany publisher with tests
